### PR TITLE
Add COMP-A, LRC-A and LINK-A support

### PR DESCRIPTION
**Pull request by grandizzy**

### CODE REVIEW

**Review by EdNoepel — COMMENTED** [review]
I'm disappointed that price models for new collaterals are still dictating gas prices, preventing the keeper from managing the transaction queue.

**Review by EdNoepel — APPROVED** [review]

**Comment by grandizzy** [comment]
> I'm disappointed that price models for new collaterals are still dictating gas prices, preventing the keeper from managing the transaction queue.

@EdNoepel so if we just remove `\"gasPrice\": \"$(dynamic_gas)\"`

from 
```echo "{\"price\": \"${bidPrice}\", \"gasPrice\": \"$(dynamic_gas)\"}"```

the keeper will take care of rest? If simple as that I can amend all files and send a PR for review

**Comment by EdNoepel** [comment]
> > I'm disappointed that price models for new collaterals are still dictating gas prices, preventing the keeper from managing the transaction queue.
> 
> @EdNoepel so if we just remove `\"gasPrice\": \"$(dynamic_gas)\"`
> 
> from
> `echo "{\"price\": \"${bidPrice}\", \"gasPrice\": \"$(dynamic_gas)\"}"`
> 
> the keeper will take care of rest? If simple as that I can amend all files and send a PR for review

Indeed, and `env/dynamic_gas.sh` can be gutted as well.

**Review by godsflaw — COMMENTED** [review]
LGTM, but I'm going to PR the removal of the dynamic gas pricing model into this too.

**Pull request merged**
