### PR TITLE
cmooney-2020032001: Add dynamic gas price to model

### PR DESCRIPTION
**Pull request by godsflaw**
This commit adds dynamic gas pricing to the models too.

### CODE REVIEW

**Comment by godsflaw** [comment]
Leaving this as a `[WIP]` until we merge up: https://github.com/makerdao/dockerized-auction-keeper/pull/18

We may also want to add USDC to #18.  You up for it @grandizzy?

**Comment by grandizzy** [comment]
@godsflaw 2 other ways for applying dynamic gas are documented here https://github.com/makerdao/dockerized-auction-keeper#using-a-dynamic-gas-price-model-for-bids  should we have all of them baked in separate scripts and leave user just to configure in environment.sh which one to apply?

**Comment by godsflaw** [comment]
> @godsflaw 2 other ways for applying dynamic gas are documented here https://github.com/makerdao/dockerized-auction-keeper#using-a-dynamic-gas-price-model-for-bids should we have all of them baked in separate scripts and leave user just to configure in environment.sh which one to apply?

Working on exactly this now.

**Comment by godsflaw** [comment]
@grandizzy going to keep this PR simpler and just include the dynamic gas changes.  This simplifies the documentation, while providing for three different dynamic gas models.  You can review when you're ready.

**Review by grandizzy — APPROVED** [review]

**Comment by grandizzy** [comment]
> Leaving this as a `[WIP]` until we merge up: #18
> 
> We may also want to add USDC to #18. You up for it @grandizzy?

Yep, I will add usdc in few

**Pull request merged**
